"""empty message

Revision ID: c6da8d88cd00
Revises: 
Create Date: 2020-05-06 17:35:54.908010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6da8d88cd00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('todos', 'string')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('string', sa.String(), autoincrement=False, nullable=True))
    op.drop_column('todos', 'name')
    # ### end Alembic commands ###
