"""empty message

Revision ID: e159af6319e4
Revises: 
Create Date: 2020-04-27 17:31:47.551987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e159af6319e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('todos', 'string')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('string', sa.String(), autoincrement=False, nullable=True))
    op.drop_column('todos', 'name')
    # ### end Alembic commands ###
